version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/next-sanity"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/snowpack-react"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/snowpack-vanilla"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/ts-jest"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/vite-vanilla"
    schedule:
      interval: "monthly"
