import type { NextPage } from "next"
import Head from "next/head"
import { useState } from "react"
import s from "styles/Home.module.scss"

const Home: NextPage = () => {
  const [count, countSet] = useState(0)

  const title = "Welcome to Next.js!"
  return (
    <div className={s.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h1>{title}</h1>
        <button onClick={() => countSet(count + 1)}>Count is: {count}</button>
      </main>
    </div>
  )
}

export default Home
